encoding: utf-8
repository: unitedstack.github.io/halo
name: Halo

github: [metadata]
defaults:
  - scope:
      path: ''
      type: posts
    values: 
      layout: default
  - scope:
      path: framework
      type: pages
    values:
      layout: framework
  - scope:
      path: started
      type: pages
    values:
      layout: started
  - scope:
      path: develop
      type: pages
    values:
      layout: develop